/**
 * Predefined caption styles
 */

import type { CaptionStyleConfig } from '../types/caption.types';

// Default caption styles available to users
export const DEFAULT_CAPTION_STYLES: CaptionStyleConfig[] = [
  {
    styleId: 'style_classic_white',
    name: 'Classic White',
    description: 'Clean white text with black outline - works on any background',
    fontFamily: 'Arial',
    fontSize: 48,
    fontWeight: 'BOLD',
    fontColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 2,
    shadowColor: '#000000',
    shadowBlur: 4,
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 90,
    animation: 'NONE',
    wordsPerLine: 8,
    isDefault: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    styleId: 'style_classic_black',
    name: 'Classic Black',
    description: 'Bold black text with white outline - great for bright videos',
    fontFamily: 'Arial',
    fontSize: 48,
    fontWeight: 'BOLD',
    fontColor: '#000000',
    outlineColor: '#FFFFFF',
    outlineWidth: 2,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 90,
    animation: 'NONE',
    wordsPerLine: 8,
    isDefault: false,
    isActive: true,
    sortOrder: 2,
  },
  {
    styleId: 'style_boxed_white',
    name: 'Boxed White',
    description: 'White text on semi-transparent black background',
    fontFamily: 'Arial',
    fontSize: 44,
    fontWeight: 'BOLD',
    fontColor: '#FFFFFF',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    backgroundPadding: 12,
    backgroundBorderRadius: 8,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 85,
    animation: 'FADE',
    animationDuration: 200,
    wordsPerLine: 8,
    isDefault: false,
    isActive: true,
    sortOrder: 3,
  },
  {
    styleId: 'style_boxed_black',
    name: 'Boxed Black',
    description: 'Black text on semi-transparent white background',
    fontFamily: 'Arial',
    fontSize: 44,
    fontWeight: 'BOLD',
    fontColor: '#000000',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    backgroundPadding: 12,
    backgroundBorderRadius: 8,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 85,
    animation: 'FADE',
    animationDuration: 200,
    wordsPerLine: 8,
    isDefault: false,
    isActive: true,
    sortOrder: 4,
  },
  {
    styleId: 'style_neon_green',
    name: 'Neon Green',
    description: 'Vibrant neon green with glow effect - perfect for gaming/tech content',
    fontFamily: 'Impact',
    fontSize: 52,
    fontWeight: 'BOLD',
    fontColor: '#39FF14',
    outlineColor: '#000000',
    outlineWidth: 3,
    shadowColor: '#39FF14',
    shadowBlur: 15,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 90,
    animation: 'FADE',
    animationDuration: 150,
    wordsPerLine: 6,
    isDefault: false,
    isActive: true,
    sortOrder: 5,
  },
  {
    styleId: 'style_gradient_pop',
    name: 'Gradient Pop',
    description: 'Bold yellow text with pop animation - attention grabbing',
    fontFamily: 'Impact',
    fontSize: 56,
    fontWeight: 'BOLD',
    fontColor: '#FFD700',
    outlineColor: '#FF4500',
    outlineWidth: 4,
    shadowColor: '#000000',
    shadowBlur: 8,
    shadowOffsetX: 4,
    shadowOffsetY: 4,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 90,
    animation: 'BOUNCE',
    animationDuration: 300,
    wordsPerLine: 5,
    isDefault: false,
    isActive: true,
    sortOrder: 6,
  },
  {
    styleId: 'style_minimal',
    name: 'Minimal',
    description: 'Clean, modern minimal look - professional feel',
    fontFamily: 'Helvetica Neue',
    fontSize: 40,
    fontWeight: 'NORMAL',
    fontColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowBlur: 3,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 60,
    maxWidth: 80,
    animation: 'FADE',
    animationDuration: 300,
    wordsPerLine: 10,
    isDefault: false,
    isActive: true,
    sortOrder: 7,
  },
  {
    styleId: 'style_bold_impact',
    name: 'Bold Impact',
    description: 'Large bold text for maximum readability',
    fontFamily: 'Impact',
    fontSize: 64,
    fontWeight: 'BOLD',
    fontColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 4,
    position: 'CENTER',
    alignment: 'CENTER',
    maxWidth: 95,
    animation: 'SLIDE_UP',
    animationDuration: 200,
    wordsPerLine: 4,
    isDefault: false,
    isActive: true,
    sortOrder: 8,
  },
  {
    styleId: 'style_karaoke',
    name: 'Karaoke Style',
    description: 'Word-by-word highlight effect - like karaoke!',
    fontFamily: 'Arial',
    fontSize: 48,
    fontWeight: 'BOLD',
    fontColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 2,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 80,
    maxWidth: 90,
    animation: 'HIGHLIGHT',
    animationDuration: 100,
    highlightColor: '#FFD700',
    wordsPerLine: 8,
    isDefault: false,
    isActive: true,
    sortOrder: 9,
  },
  {
    styleId: 'style_netflix',
    name: 'Netflix Style',
    description: 'Cinema-quality subtitles like streaming services',
    fontFamily: 'Netflix Sans',
    fontSize: 42,
    fontWeight: 'NORMAL',
    fontColor: '#FFFFFF',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    backgroundPadding: 8,
    backgroundBorderRadius: 4,
    position: 'BOTTOM',
    alignment: 'CENTER',
    marginBottom: 50,
    maxWidth: 80,
    animation: 'NONE',
    wordsPerLine: 12,
    isDefault: false,
    isActive: true,
    sortOrder: 10,
  },
];

// Get style by ID
export const getStyleById = (styleId: string): CaptionStyleConfig | undefined => {
  return DEFAULT_CAPTION_STYLES.find(style => style.styleId === styleId);
};

// Get default style
export const getDefaultStyle = (): CaptionStyleConfig => {
  const defaultStyle = DEFAULT_CAPTION_STYLES.find(style => style.isDefault);
  if (!defaultStyle) {
    throw new Error('No default caption style configured');
  }
  return defaultStyle;
};

// Get all active styles sorted by sortOrder
export const getActiveStyles = (): CaptionStyleConfig[] => {
  return DEFAULT_CAPTION_STYLES
    .filter(style => style.isActive)
    .sort((a, b) => a.sortOrder - b.sortOrder);
};

// Style ID to display name mapping for WhatsApp menus
export const STYLE_MENU_OPTIONS = DEFAULT_CAPTION_STYLES
  .filter(style => style.isActive)
  .sort((a, b) => a.sortOrder - b.sortOrder)
  .map(style => ({
    id: style.styleId,
    title: style.name,
    description: style.description,
  }));
